[package]
name = "dfhack-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.27.1"

[build-dependencies]
protobuf-codegen-pure = "2.27.1"
dfhack-proto-srcs = { path = "../dfhack-proto-srcs" }
regex = "1"
heck = "0.4"
quote = "1.0.18"
