[package]
name = "dfhack-proto-srcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"

[build-dependencies]
reqwest = {version="0.11.10",features=["blocking"]}
zip = "0.6.2"
