name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish dfhack-proto-srcs
      if: startsWith(github.ref, 'refs/tags/v')
      run: cargo publish -p dfhack-proto-srcs
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - name: Publish dfhack-proto
      if: startsWith(github.ref, 'refs/tags/v')
      run: cargo publish -p dfhack-proto
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - name: Publish dfhack-remote
      if: startsWith(github.ref, 'refs/tags/v')
      run: cargo publish -p dfhack-remote
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
